### ISSUE TITLE
Running gotenberg in GKE

### ISSUE THREAD

**Issue by trelore** [thecodingmachine/gotenberg#53]
Hi!

This looks amazing, we are looking forward to using this within our k8s cluster, however we're struggling to get the image up and running.

Our k8s file looks like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  labels:
    app: gotenberg
spec:
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: thecodingmachine/gotenberg:4
          ports:
            - name: gotenberg
              containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: gotenberg
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: gotenberg
      port: 3000
      targetPort: 3000
```
## Output
The deployment has the following logs and fails to start
```
➜ kubectl logs gotenberg-74d485d685-m6frr
⇨ Gotenberg 4.2.0
⇨ Chrome headless started with PM2
⇨ warming-up Chrome headless
⇨ Chrome headless restarted with PM2
⇨ warming-up Chrome headless
⇨ Chrome headless restarted with PM2
⇨ warming-up Chrome headless
⇨ Chrome headless restarted with PM2
⇨ warming-up Chrome headless
⇨ Chrome headless restarted with PM2
⇨ warming-up Chrome headless
⇨ Chrome headless restarted with PM2
⇨ warming-up Chrome headless
⇨ error: failed to launch Chrome headless
```

If we're doing something wrong it'd be great to see a larger demo/example in the docs for k8s.

## Your Environment
```
➜  kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gulien** [comment]
Hello!

Hmm weird 🤔 maybe insufficient default values for CPU / memory requests? Does it happens to with a version < 4.2?

**Comment by trelore** [comment]
Yeah, that seemed to sort the issue, thanks.

Would you mind if I created a PR later today for an example k8s file? 

We've set the following for the time being;
```
          resources:
            limits:
              memory: 512Mi
              cpu: 0.2
            requests:
              memory: 512Mi
              cpu: 0.2
```
